package model.message;

public enum OperationType {
	START, REGISTER, LOGIN, LOGOUT, GET_USER, NEW_GAME, GAME, RESULTS, WORDS, ERROR, OK, REPORT, NOT_FOUND, GET_NUM_OF_LOGGED_USERS, GET_USERS, GET_PLAYED_GAMES;
}
